  raw_train_normal_path: data/01_raw/train/NORMAL
  raw_train_pneumonia_path: data/01_raw/train/PNEUMONIA
  raw_val_normal_path: data/01_raw/val/NORMAL/
  raw_val_pneumonia_path: data/01_raw/val/PNEUMONIA
  raw_test_normal_path: data/01_raw/test/NORMAL/
  raw_test_pneumonia_path: data/01_raw/test/PNEUMONIA